### ISSUE TITLE
Installing"Data Analysis" : error computer not responding 

### ISSUE THREAD

**Issue by pranavpatil1987** [swirldev/swirl#228]
Please help with following issue

I have installed swirl package:          install.packages("swirl")
and I could also install R Programming package 

but whenever I am trying to install "Data Analysis" part of it my computer is not responding 
I am using following syntax
library(swirl)
install_from_swirl("Data Analysis")
swirl()

**Comment by KK0h** [comment]
![install swirl r prog](https://cloud.githubusercontent.com/assets/16876258/12774908/5fd76a82-ca84-11e5-973d-97fe97ea6110.jpg)

Hi, how long does it take to install R Programming, using install_from_swirl? My screen seemed to hang after the line install_from_swirl("R Programming").

**Comment by seankross** [comment]
@KK0h see #387 and let me know if that helps.

**Comment by KK0h** [comment]
Thanks for replying. I realised that during the period of non-response, the computer was actually downloading the file (I also tried downloading the zip file found in GitHub). Because I tried so many times, in the end, I ended up with three copies of the downloaded file, from which I successfully installed. I think it's just that the computer doesn't show any message during the download, unlike the usual pop up downloading tab which shows the progress of downloading, and when I look in the folder for the download file, the name is there but has zero bytes or no content, so I thought it failed. The process took about 20 minutes, so luckily I hung around and waited when nothing seemed to be happening.
