### ISSUE TITLE
Sources update for swirl on Linux install

### ISSUE THREAD

**Issue by charl** [swirldev/swirl#252]
https://github.com/swirldev/swirl/wiki/Installing-swirl-on-Linux lists the first step to install as:

```
$ sudo sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu precise/" >> /etc/apt/sources.list'
```

Most modern Linux distros recommend you not edit /etc/apt/sources.list directly and rather place any additions you want to outlive a package update in /etc/apt/sources.list.d. With that in mind the command above should rather be:

```
$ sudo sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu precise/" >> /etc/apt/sources.list.d/cran.list
```

**Comment by WilCrofter** [comment]
Thanks, @charl . I've essentially pasted your words into the wiki. I'll leave the issue open since I've done this in a rush.

**Comment by joegodbehere** [comment]
Thanks for including these instructions. :)

There's a missing trailing single quote on the new text. It should be:
`$ sudo sh -c 'echo "deb http://cran.rstudio.com/bin/linux/ubuntu precise/" >> /etc/apt/sources.list.d/cran.list'`

Note, that using either of these instructions on a more modern distribution (e.g. Ubuntu 14.10, and probably 14.04) breaks the install, since the package at that source depends on libtiff4, but this has been removed (superseded by libtiff5). Happily, users can (and should) skip that step entirely, since a compatible package (R 3.1.1) is already included in that distribution.
