### ISSUE TITLE
Evaluate() not working with anonymous function

### ISSUE THREAD

**Issue by qabadai** [swirldev/swirl#275]
Have finished creating the evaluate function and it works, but when it asks me to evaluate an anonymous function by typing in this:

Type the following command and then we'll discuss how it works: evaluate(function(x){x+1}, 6)

I get this output.
> evaluate(function(x){x+1}, 6)
[1] 7

| Almost! Try again. Or, type info() for more options.

| Just type the command evaluate(function(x){x+1}, 6)

I've also tried skip() and it fails to get past this question.

> skip()

| Entering the following correct answer for you...

> evaluate(function(x){x+1}, 6)

| Try again. Getting it right on the first try is boring anyway! Or, type info() for more options.

| Just type the command evaluate(function(x){x+1}, 6)

**Comment by seankross** [comment]
This is tricky. It appears to be working. Let me try to reproduce this.

**Comment by ckaufman21** [comment]
I'm having the same issue. I tried typing it, tried copying and pasting it, tried skipping the question, but can't get past it.

| Try again. Getting it right on the first try is boring anyway! Or, type info() for more options.

| Just type the command evaluate(function(x){x+1}, 6)

> evaluate(function(x){x+1}, 6)
[1] 7

| You almost had it, but not quite. Try again. Or, type info() for more options.

| Just type the command evaluate(function(x){x+1}, 6)

> skip()

| Entering the following correct answer for you...

> evaluate(function(x){x+1}, 6)

| You almost had it, but not quite. Try again. Or, type info() for more options.

| Just type the command evaluate(function(x){x+1}, 6)

> skip()

| Entering the following correct answer for you...

> evaluate(function(x){x+1}, 6)

| You almost had it, but not quite. Try again. Or, type info() for more options.

| Just type the command evaluate(function(x){x+1}, 6)

> evaluate(function(x){x+1}, 6)
[1] 7

| You're close...I can feel it! Try it again. Or, type info() for more options.

| Just type the command evaluate(function(x){x+1}, 6)

> skip()

| Entering the following correct answer for you...

> evaluate(function(x){x+1}, 6)

| Not quite right, but keep trying. Or, type info() for more options.

| Just type the command evaluate(function(x){x+1}, 6)

**Comment by seankross** [comment]
Hi @ckaufman21 and @qabadai,

How did each of you implement `evaluate`?

**Comment by ckaufman21** [comment]
I'm not sure what you mean specifically by "implement". It's honestly hard to remember now, but I think it was written in the script pop-up window and saved, and was working properly for the testing questions before this one.

I've at least now gone out to the main menu and moved on to another lesson. At first it kept forcing me to the same spot where I was stuck.

**Comment by seankross** [comment]
Hi @ckaufman21 and @qabadai,

This may be an issue with the version of Swirl that you have installed. Try `install.packages("swirl")` to get the latest version. Let me know if that fixes the problem or if you're still having issues.

**Comment by Eroche5** [comment]
@seankross After updating the swirl package I am no longer having this issue.

**Comment by seankross** [comment]
This issue should be resolved by swirl/swirl_courses@5e7f439fdb7ff63dee6c35ddf9353ba8e841cff7. Please download the latest version of the R Programming course with the command `install_from_swirl("R Programming")`. If this problem persists please reopen this issue.

**Comment by realowded** [comment]
Hello sean,
 I am stuck at the evaluate question...and I couldn't skip...

# You can pass functions as arguments to other functions just like you can pass
# data to functions. Let's say you define the following functions:
#
# add_two_numbers <- function(num1, num2){
#    num1 + num2
# }
#
# multiply_two_numbers <- function(num1, num2){
#	num1 * num2
# }
#
# some_function <- function(func){
#    func(2, 4)
# }
#
# As you can see we use the argument name "func" like a function inside of 
# "some_function()." By passing functions as arguments 
# some_function(add_two_numbers) will evaluate to 6, while
# some_function(multiply_two_numbers) will evaluate to 8.
# 
# Finish the function definition below so that if a function is passed into the
# "func" argument and some data (like a vector) is passed into the dat argument
# the evaluate() function will return the result of dat being passed as an
# argument to func.
#
# Hints: This exercise is a little tricky so I'll provide a few example of how
# evaluate() should act:
#    1. evaluate(sum, c(2, 4, 6)) should evaluate to 12
#    2. evaluate(median, c(7, 40, 9)) should evaluate to 9
#    3. evaluate(floor, 11.1) should evaluate to 11

evaluate <- function(func, dat){
  # Write your code here!
  # Remember: the last expression evaluated will be returned! 
}

i've tried many times.please help me to finish the code .thanks a lot

**Comment by seankross** [comment]
Hi @realowded,

You can find answers to the function questions [here](https://gist.github.com/seankross/912fe3b9f19a91b0a7bd). In the future, please open a new issue if you have a question.

**Comment by realowded** [comment]
SeanKross, You are highly appreciated.

**Comment by henloy77** [comment]
I tried the answer to the evaluate exercise,
 evaluate <- function(func, dat){
  func(dat)
}
however it still says not quite right

**Comment by rks99974** [comment]
evaluate (func, dat)
func is without parenthesis so R consider it as a character so just convert it as a function  using as.function()
**evaluate <- function(func, dat){
  as.function(func)
  func(dat)
}**
