### ISSUE TITLE
Skips carried over from previous session

### ISSUE THREAD

**Issue by leimdorfer** [swirldev/swirl#286]
I am working through the courses for Coursera. Here's what happened:

I did the first swirl task - submitted - got the credit.
I went back to look at it to check something and skipped everything because I just wanted to read it.
I started and finished the second swirl task with NO skips (occasional typos and mistakes, but zero skips). 
No credit given because of "too many skips"

RStudio: Version 0.98.1091
R version 3.1.2 (2014-10-31)

**Comment by ncarchedi** [comment]
What version of swirl are you using? packageVersion("swirl")

**Comment by leimdorfer** [comment]
2.2.21

**Comment by Brufico** [comment]
Hello,
I have the same issue. Not really a big problem, just annoying. Also, as I work through more lessons, the problems keeps happening (swirl says i cannot get credit because i skipped questions, which i have'nt).
 If i switch to another instance of swirl on my laptop, I can complete the lessons and get credit. As I said, it is not a really big problem, but it looks like a real bug.

**Comment by seankross** [comment]
Have you tried reinstalling swirl?

**Comment by Brufico** [comment]
Hi Sean,
No, It did'nt occur to me.
I will try it.
Thank you.

Bruno

Le 04/10/2015 19:58, Sean Kross a écrit :
>
> Have you tried reinstalling swirl?
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/swirldev/swirl/issues/286#issuecomment-145369799>.
>

-- 
Bruno Fischer
