### ISSUE TITLE
Always encounter errors when going through Module 10 of "Statistical Inference"

### ISSUE THREAD

**Issue by tywanghnu** [swirldev/swirl#311]
Errors occur when swirl tries to plot something after loading "ggplot2" with varied error messages.

The following is one of those error messages:

| Here's a plot to show what we mean. The shaded portion represents 5% of the area under the curve and those X values in it are those for which the probability that X>C is 5%.

Error: Results must be all atomic, or all data frames

| Leaving swirl now. Type swirl() to resume.

**Comment by AllWalker** [comment]
After loading swirl(), enter the command: 

delete_progress("username") 

where username is whatever you have been calling yourself on loading swirl. This deletes any half-finished modules (which seem to be what are causing the problems in the first place) but will not wipe any scores you have uploaded to Coursera.

**Comment by seankross** [comment]
Hi @AllWalker,

swirl cannot delete progress already logged on Coursera.

**Comment by AllWalker** [comment]
Yeah, that is what I said.

**Comment by seankross** [comment]
Hi @AllWalker,

There's no way that swirl could delete progress logged to Coursera. Only a Coursera course instructor could do that.

**Comment by AllWalker** [comment]
Hi @seankross,

Yes, that's right. Again, that is exactly what I said. From the last sentence of my first post:
"... but will NOT wipe any scores you have uploaded to Coursera."

But it will delete anything and everything apart from that. Which could be a problem if you have lots of half-finished modules and results that have not been uploaded.

**Comment by seankross** [comment]
Hi @AllWalker,

I'm sorry I'm not understanding the question that you have or the issue that you're raising. The purpose of the `delete_progress()` functions is to delete a users progress in swirl. If you have a question or there's an issue you'd like to raise with swirl please let me know.

**Comment by AllWalker** [comment]
@seankross 

I'm confused too. I'm not asking a question and I'm not raising an issue. I was replying to @tywanghnu 's question above - swirl crashing at that particular point was fixed for me by deleting my progress.

Some context: a few days ago I encountered the same problem as @tywanghnu with swirl. I found this thread (and a few others like it on Coursera and other places) by Googling the problem. Lots of people were finding the same issue but no one had posted any solutions. Despite this post being five months old and it detailing common problem, I could not find any specific advice or explanations. Eventually I gave delete_progress() a shot and it worked for me. So, to stop other people having to search in vain and experiment on their own, I posted the _solution_ to the problem that _other people_ were asking. I was _not_ asking a question of my own here.

I guess I must have done something wrong - are only devs allowed to answer the questions here? But given how simple my solution was to a problem serious enough to stop swirl from working, I felt I had to share it. If the solution, any solution, had been posted here, it would have saved me a lot of time and effort. 

Anyway, I thought it was clear that I know that swirl doesn't delete results on Coursera, since I mention exactly that in myfirst post. And I also thought it was clear that I know how delete_progress() works, since I outline both how and why to use it. Next time I come across a nugget of wisdom I'll be clearer in how I share it. But I wouldn't have had to share it at all of this post, or any of the others asking the same question, had been answered.

**Comment by seankross** [comment]
Hi @AllWalker,

This is just a case of me being dense - I completely misunderstood that you were suggesting `delete_progress()` as a solution to @tywanghnu's problem. You haven't done anything wrong and of course all are encouraged to answer questions on the these issues. 

It's common that users will ask a question or raise an issue in the comments of an unrelated issue. I'm sure this is because many swirl users are also new to GitHub, and it's okay with me that new users do this. I thought that this was the case with your comment. I was under the impression that you expected `delete_progress()` to delete what swirl submits to Coursera and you were complaining that `delete_progress()` lacked this functionality. I see now I was completely off base and I'm sorry if I made you feel uncomfortable or if I wasted your time.

Thank you for finding a way to solve this problem! Hopefully it help those following in your Google search footsteps.
