### ISSUE TITLE
Provide option to specify coding standard preferences

### ISSUE THREAD

**Issue by khughitt** [swirldev/swirl#363]
Would it be possible to provide an option to control which coding style is used for the course materials,   or at least, provide some control over common coding style decisions?

For instance, allowing the instructor to specify whether to use "<-" or "=" for variable assignment. Currently, it appears that it is hard-coded to require the use of "<-".

**Comment by seankross** [comment]
Hi Keith! 

So it's up to the course author to specify what expressions swirl will accept as a valid answer. The course author probably specified `<-` because they thought it was good style. Anyone writing a new swirl course could write their course so that both `<-` and `=` are valid. Remember that on Mac `option` + `-` is a shortcut for ` <- ` in the R console. Happy Halloween :jack_o_lantern: and give everyone at CBCB my love!

**Comment by khughitt** [comment]
Hey Sean,

That sounds good -- I suppose I can always just fork the course and modify things there, too. I actually tend to use mostly vim-r, which also has a shortcut for inserting the `<-`.

In my case, it's more of philosophical opposition to the use of `<-`. I've been holding out, hoping that the community might move towards using `=` assignment, but it doesn't look like that is going to happen, so it may be time to just bite the bullet and start using the arrow assignment! :confused: 

Keep up the good work!
