### ISSUE TITLE
Install swirl - R (or RStudio) crashes and kapersky tells me there is a Trojan.

### ISSUE THREAD

**Issue by sch56** [swirldev/swirl#376]
Windows 8.1 Enterprise
R 3.2.2
RStudio  0.99.489

> install.packages("swirl")
It starts installing and then crashes.  RStudio reports a 'Fatal Error'.  R simply crashes.
Kaspersky then pops up and tells me there is a Trojan in the R binaries folder and neutralizes this.
R (or RStudio), whichever I tried it from now no longer works and has to be reinstalled.
From Kaspersky Quarantine log:
11/12/2015 2:12:20 p.m.	Quarantined	unknown object: 110 PDM:Trojan.Win32.Generic	c:\program files\rstudio\bin\x64\rsession.exe	Medium

**Comment by seankross** [comment]
Wow this is a first! It looks like it thinks all of R is a trojan! You'll have to indicate to Kaspersky that R and RStudio should be trusted.

**Comment by sch56** [comment]
The following are the screen dumps that I get.  Kaspersky seems very insistent that there is somthing wrong with the swirl package.

I am fine using R console and R Studio until this attempt to install swirl.
[cid:image004.jpg@01D13659.2FF8AA70]

[cid:image003.png@01D13658.5980F2E0]

At this point Windows is now unstable and a restart is necessary.  R Studio is also not usable until reinstalled.

I am not at all happy about trusting the swirl package.

Simon Harrison

**Comment by seankross** [comment]
Hi Simon,

For some reason I can't see the images you've attached.

I'm the maintainer of swirl and therefore I'm responsible for all of it's source code, behaviors, and features. The swirl package has been downloaded over half a million times by people all over the world using a wide variety of software and hardware configurations. When you use `install.packages("swirl")` you are downloading a copy of swirl from [CRAN](https://www.r-project.org/), which is an archive for R packages maintained and managed by some of the best minds in statistical software. CRAN has a rigorous submission procedure that ensures that software it distributes is safe and compatible with the most widely used operating systems.

Swirl does **not** do any other following:

- Modify the operating system
- Change system settings
- Modify the Windows registry
- Send information to a server

Swirl has two behaviors that might be triggering Kaspersky:

- swirl downloads swirl courses and writes them to your hard drive
- swirl executes R code

Swirl courses and the swirl software itself are two separate entities, that way anyone can write a course to use with swirl, and authors of swirl courses can distribute changes to their courses quickly. Swirl also executes R code and it instructs the user to execute R code since swirl's purpose is to teach users how to use R.

Let me know if you have any other questions about swirl's security. Unfortunately I don't know enough about how Kaspersky works in order to get it recognize that swirl is safe to use. If you could send those screenshots along that would be helpful, especially in the event that other users have this problem.
