### ISSUE TITLE
Why I can't received credit for completing swirl course on Coursera.org?

### ISSUE THREAD

**Issue by andywarta** [swirldev/swirl#413]
I'm try to completed R Programming Course (**R Programming Basic Building Blocks** and **R Programming Workspace and Files**) using swirl, but when i try to get credit for completing the course  there's error like this:
![image](https://cloud.githubusercontent.com/assets/17173884/13165074/85654156-d6ec-11e5-80c2-1d19fc23058a.png)
Please help
Thanks

**Comment by seankross** [comment]
When you completed the assignment were you connected to the internet?

**Comment by RuchaRaje** [comment]
Hi,
I am facing the same issue when I try to submit the assignment, and I have not connected to any proxy server. Thanks.

**Comment by SMawri** [comment]
Hi,
I am facing the same issue when I try to submit the assignment.

Please help 
![swirl error building blocks](https://cloud.githubusercontent.com/assets/18375254/14950811/28bd7774-1072-11e6-8925-ccb511a65fb4.JPG)

Thanks

**Comment by seankross** [comment]
@SMawri try connecting to the internet through a different connect if possible.

**Comment by SMawri** [comment]
Hi Sean,

Sorry but i didn't understand what your are saying.

I tried on my laptop using my phone internet but it didn't happened.

So help me on this.

Is it necessary to complete the assignment and post the grade on Coursera
because i am thinking to practice and complete the assignment and since i
am facing the problem while posting so i will not try to post it.

Does it will affect my certification if i didn't post my grade on the
Website although i am completing the assignment.


Thanks ,
Sandeep M.

**Comment by seankross** [comment]
@SMawri The swirl assignments are optional and you can get full marks in the course without completing them.

**Comment by SMawri** [comment]
Thanks Sean

I would complete the Swirl assignments because it make me thorough with the
R commands and programming thing but as I am facing problem while posting
the results i won't post it on Coursera.


Thanks and Regards,
Sandeep M.
