### ISSUE TITLE
Swirl displaying error message when the assignment token is given

### ISSUE THREAD

**Issue by gitagowda** [swirldev/swirl#428]
Hi, 

I am trying to get the credit for my assignment in SWIRL but when I copy paste my assignment token, it's displaying the following error:
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Peer certificate cannot be authenticated with given CA certificates

| Leaving swirl now. Type swirl() to resume.
I am connected to the internet while taking the assignment and I have tried with multiple assignment tokens but all the time I am getting the same error. How will I solve this issue and get credits for my assignment? Please help!

**Comment by seankross** [comment]
Hi @gitagowda,

My best suggestion is that if you are using a laptop, use a different internet connection when submitting your assignment. Otherwise, try completing the assignment on a different computer that uses a different internet connection. These assignments are optional because not everyone is able to submit them. Sorry for the inconvenience.

**Comment by gitagowda** [comment]
Hey thanks for this suggestion and it really worked! I connected to the other network and it worked.

Grade submission succeeded!

| Excellent work!

| You've reached the end of this lesson! Returning to the main menu...

Thanks for the help!

**Comment by seankross** [comment]
I'm happy it worked. Let me know if you run into any other issues.
