### ISSUE TITLE
swirl errors out in the Functions module

### ISSUE THREAD

**Issue by sahaisiddharth** [swirldev/swirl#434]
Hi

When I go through the functions module as soon as it reaches a certain stage it exits swirl with the following error:

| In the following question you will be asked to modify a script that will
| appear as soon as you move on from this question. When you have finished
| modifying the script, save your changes to the script and type submit()
| and the script will be evaluated. There will be some comments in the
| script that opens up, so be sure to read them!

...

  |==========                                                         |  14%

| The last R expression to be evaluated in a function will become the return
| value of that function. We want this function to take one argument, x, and
| return x without modifying it. Delete the pound sign so that x is returned
| without any modification. Make sure to save your script before you type
| submit().

Error in editor(file = file, title = title) : 
  argument "name" is missing, with no default

| Leaving swirl now. Type swirl() to resume.

**Comment by seankross** [comment]
Are you using R with the RGui, with RStudio, in the terminal, or through
some other method?

**Comment by guiml** [comment]
I have a similar issue in the **Getting and Cleaning Data** when I reach the following step:

`| Let's take it a step further. I just opened an R script for
| you that contains a partially constructed call to
| summarize(). Follow the instructions in the script
| comments.
| 
| When you are ready to move on, save the script and type
| submit(), or type reset() to reset the script to its
| original state.

Error in editor(file = file, title = title) : 
  argument "name" is missing, with no default

| Leaving swirl now. Type swirl() to resume.`

I use **RStudio in Windows 10 64b**

**Version 0.99.892 **– © 2009-2016 RStudio, Inc.
Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/538.1 (KHTML, like Gecko) rstudio Safari/538.1 Qt/5.4.1

It appears to have something related to a fail when trying to open a file in my local RStudio...

Does anyone have a light on this?

**Comment by sahaisiddharth** [comment]
i am also using RStudio in Windows 10 64b.

**Comment by bkkesseler** [comment]
I am receiving the same error, with R 3.2.4 and RStudio 0.99.893 Windows 10 64b.

**Comment by seankross** [comment]
What do all of you get as a result of `getOption("editor")`?

**Comment by bkkesseler** [comment]
> getOption("editor")
function (name, file, title) 
{
    if (is.null(name) || is.function(name)) {
        if (is.null(name)) {
            if (!is.null(file) && nzchar(file)) 
                targetFile <- file
            else targetFile <- scratchFile
        }
        else {
            functionSrc <- .rs.deparseFunction(name, TRUE, FALSE)
            targetFile <- scratchFile
            writeLines(functionSrc, targetFile)
        }
        if (.Call("rs_editFile", targetFile)) {
            newFunc <- try(eval.parent(parse(targetFile)), silent = TRUE)
            if (inherits(newFunc, "try-error")) {
                stop(newFunc, "You can attempt to correct the error using ", 
                  title, " = edit()")
            }
            return(newFunc)
        }
        else {
            stop("Error occurred while editing function '", name, 
                "'")
        }
    }
    else edit(name, file, title, editor = defaultEditor)
}

**Comment by sahaisiddharth** [comment]
following is the result:

> getOption("editor")
function (name, file, title) 
{
    if (is.null(name) || is.function(name)) {
        if (is.null(name)) {
            if (!is.null(file) && nzchar(file)) 
                targetFile <- file
            else targetFile <- scratchFile
        }
        else {
            functionSrc <- .rs.deparseFunction(name, TRUE)
            targetFile <- scratchFile
            writeLines(functionSrc, targetFile)
        }
        if (.Call("rs_editFile", targetFile)) {
            newFunc <- try(eval.parent(parse(targetFile)), silent = TRUE)
            if (inherits(newFunc, "try-error")) {
                stop(newFunc, "You can attempt to correct the error using ", 
                  title, " = edit()")
            }
            return(newFunc)
        }
        else {
            stop("Error occurred while editing function '", name, 
                "'")
        }
    }
    else edit(name, file, title, editor = defaultEditor)
}
<environment: 0x000000000dc867a0>

**Comment by seankross** [comment]
Thanks, I'll get to the bottom of this.

**Comment by seankross** [comment]
Hello all,

Before you start swirl in RStudio, try entering `options(editor = "internal")`. Please let me know if that improves your situation.

**Comment by sacooper74** [comment]
hey seankross - that works for me, the script now opens in R Editor... i'm on Version 0.99.893 – © 2009-2016 RStudio, Inc.

cheers, steve

**Comment by sahaisiddharth** [comment]
Thanks @seankross , it works fine now.

**Comment by brokawq** [comment]
This works for me as well!

Thank you

**Comment by ljr1984** [comment]
This works for me too!!
Thanks~

**Comment by zlf15197** [comment]
thanks，@seankross,it also works for me !
but i am wondering why it couldn't appear in the source windows as before?

**Comment by seankross** [comment]
@zlf15197 I'm working on it. It has to do with the new version of RStudio so it wasn't a change I could anticipate well.

**Comment by sidnair79** [comment]
thanks. this solution works

**Comment by Wrosinski** [comment]
Had the same problem, worked for me too.
Thanks!

**Comment by ENHarry** [comment]
I just had the same problem and your solution worked for me as well. Thanks @seankross

**Comment by micheldeleeuw** [comment]
Thanks!

**Comment by fdon** [comment]
Thanks, worked for me as well

**Comment by MichaelBaraz** [comment]
I had this problem too. After I ran the options(editor = "internal") command and reran swirl for Regression Models, Least Squares Estimation, it gets to the manipulate function and pops up an editor window with the function instead of running the function. The swirl lesson says to click on the gear icon to display the manipulate window if it disappears... there is no gear (I presume because manipulate isn't running). Am I supposed to run manipulate manually somehow?

Also, when it is supposed to be running manipulate you get choices on some values... since manipulate wasn't running I couldn't answer the questions so I typed "0" to exit but that doesn't work (though the program says that is how to exit).

**Comment by cindyyeon** [comment]
sean kross~ Thank you. Your advice helps me get through the problem!!!

**Comment by Sindhuragudipati** [comment]
This works for me as well

**Comment by maheshwickramarachchi** [comment]
hi,

I also have the same problem. i tried all the solution given. but still it remains same .

Please help me

**Comment by pauljkeenan** [comment]
thank you sean kross x

**Comment by cnik343** [comment]
the solution worked fine for me, many thanks...
also, you don't have to restart swirl to make the change...
- use `play()` to pause swirl
- then use the `options(editor = "internal") ` command given by seankross
- then resume swirl with `nxt()`

**Comment by statistinks** [comment]
solution worked! thanks!

**Comment by datageek2709** [comment]
Thanks a lot @seankross ! The solution works like a charm and I can now open the editor in rStudio. 

Just out of curiosity, what might have been at the root of this problem?

**Comment by ishgupta** [comment]
Hello,

It worked for me too! but could anyone please comment on how does the command actually function?

Thanks!

**Comment by inthse** [comment]
Thanks, this worked for me.

**Comment by gauravbansal20nov** [comment]
@seankross Thx, really appreciated. I am able to see the script now... :+1:

**Comment by kislay95** [comment]
@seankross  That Really Helped.
Thank you

**Comment by sudhakarb** [comment]
I am having a similar probelm... Please help!
What shall I call you? sudh

| Would you like to continue with one of these lessons?

1: R Programming Functions
2: No. Let me start something new.

Selection: 1



> | The last R expression to be evaluated in a function will become the return value of
> | that function. We want this function to take one argument, x, and return x without
> | modifying it. Delete the pound sign so that x is returned without any modification.
> | Make sure to save your script before you type submit().
> 
> > myfunc <- function(x) {x}
> > myfunc(2)
> [1] 2
> > submit
> function () 
> {
>     invisible()
> }
> <environment: namespace:swirl>
> > submit()
> 
> | Sourcing your script...
> 
> 
> | Not quite, but you're learning! Try again.
> 
> | Make sure to delete the pound sign so the last expression in the function is just x.
> 
> >

**Comment by kapilparashar** [comment]
Hi every one
I am getting same problem after using the instruction given above by Mr. Seankros.
Please suggest


> options(editor = "internal")
> library(swirl)

| Hi! I see that you have some variables saved in your workspace. To keep
| things running smoothly, I recommend you clean up before starting swirl.

| Type ls() to see a list of the variables in your workspace. Then, type
| rm(list=ls()) to clear your workspace.

| Type swirl() when you are ready to begin.

> ls()
 [1] "a"               "b"               "bar"             "baz"            
 [5] "boring_function" "c"               "cnames"          "con"            
 [9] "count"           "d1"              "d2"              "data1"          
[13] "data2"           "data3"           "dt"              "f"              
[17] "flags"           "i"               "ints"            "k"              
[21] "m"               "mean"            "my_char"         "my_data"        
[25] "my_div"          "my_matrix"       "my_matrix2"      "my_mean"        
[29] "my_na"           "my_name"         "my_seq"          "my_sqrt"        
[33] "my_vector"       "new.y"           "num_vect"        "ok"             
[37] "old.dir"         "patients"        "r"               "remainder"      
[41] "t1"              "t2"              "t3"              "t4"             
[45] "tf"              "uncle"           "USArrest"        "USArrests"      
[49] "val"             "vec2"            "vect"            "vect2"          
[53] "viewinfo"        "x"               "xx"              "y"              
[57] "z"              
> rm(list=ls())
> swirl()

| Welcome to swirl! Please sign in. If you've been here before, use the same
| name as you did then. If you are new, call yourself something unique.

What shall I call you? kapil

| Would you like to continue with one of these lessons?

1: R Programming Dates and Times
2: R Programming Functions
3: No. Let me start something new.

Selection: 3

| Please choose a course, or type 0 to exit swirl.

1: R Programming
2: Take me to the swirl course repository!

Selection: 1

| Please choose a lesson, or type 0 to return to course menu.

 1: Basic Building Blocks      2: Workspace and Files     
 3: Sequences of Numbers       4: Vectors                 
 5: Missing Values             6: Subsetting Vectors      
 7: Matrices and Data Frames   8: Logic                   
 9: Functions                 10: lapply and sapply       
11: vapply and tapply         12: Looking at Data         
13: Simulation                14: Dates and Times         
15: Base Graphics             

Selection: 9


  |                                                                            
  |                                                                      |   0%

| Functions are one of the fundamental building blocks of the R language. They
| are small pieces of reusable code that can be treated like any other R
| object.

...


  |                                                                            
  |=                                                                     |   2%
| If you've worked through any other part of this course, you've probably used
| some functions already. Functions are usually characterized by the name of
| the function followed by parentheses.

...


  |                                                                            
  |===                                                                   |   4%
| Let's try using a few basic functions just for fun. The Sys.Date() function returns a string representing today's date. Type Sys.Date() below and see what happens.

> Sys.Date()
[1] "2016-07-11"

| You're the best!


  |                                                                            
  |====                                                                  |   6%
| Most functions in R return a value. Functions like Sys.Date() return a value based on your computer's environment, while other functions manipulate input data in
| order to compute a return value.

...


  |                                                                            
  |======                                                                |   8%
| The mean() function takes a vector of numbers as input, and returns the average of all of the numbers in the input vector. Inputs to functions are often called
| arguments. Providing arguments to a function is also sometimes called passing arguments to that function. Arguments you want to pass to a function go inside the
| function's parentheses. Try passing the argument c(2, 4, 5) to the mean() function.

> mean(c(2,4,5))
[1] 3.666667

| Keep working like that and you'll get there!


  |                                                                            
  |=======                                                               |  10%
| Functions usually take arguments which are variables that the function operates on. For example, the mean() function takes a vector as an argument, like in the case
| of mean(c(2,6,8)). The mean() function then adds up all of the numbers in the vector and divides that sum by the length of the vector.

...


  |                                                                            
  |=========                                                             |  12%
| In the following question you will be asked to modify a script that will appear as soon as you move on from this question. When you have finished modifying the
| script, save your changes to the script and type submit() and the script will be evaluated. There will be some comments in the script that opens up, so be sure to
| read them!

...


  |                                                                            
  |==========                                                            |  14%
| The last R expression to be evaluated in a function will become the return value of that function. We want this function to take one argument, x, and return x
| without modifying it. Delete the pound sign so that x is returned without any modification. Make sure to save your script before you type submit().

>   x
Error: object 'x' not found
> # You're about to write your first function! Just like you would assign a value 
> # to a variable with the assignment operator, you assign functions in the following
> # way:
> #
> # function_name <- function(arg1, arg2){
> ## Manipulate arguments in some way
> ## Return a value
> # }
> #
> # The "variable name" you assign will become the name of your function. arg1 and
> # arg2 represent the arguments of your function. You can manipulate the arguments
> # you specify within the function. After sourcing the function, you can use the 
> # function by typing:
> # 
> # function_name(value1, value2)
> #
> # Below we will create a function called boring_function. This function takes
> # the argument `x` as input, and returns the value of x without modifying it.
> # Delete the pound sign in front of the x to make the function work! Be sure to 
> # save this script and type submit() in the console after you make your changes.
> 
> boring_function <- function(x) {
+   x
+ }
> submit()

| Sourcing your script...


| Not quite! Try again.

| Make sure to delete the pound sign so the last expression in the function is just x.

**Comment by seankross** [comment]
@kapilparashar can you send a screenshot instead?

**Comment by kapilparashar** [comment]
Please find below screenshot.

[image: Inline image 2]

**Comment by seankross** [comment]
@kapilparashar Can you please post the image directly to GitHub? I can't see it.

**Comment by kapilparashar** [comment]
![image](https://cloud.githubusercontent.com/assets/20329015/16737840/c55b5a0c-4758-11e6-86fb-5d711d37ab11.png)

**Comment by seankross** [comment]
@kapilparashar It looks like the script editor isn't opening for you. You might have better luck using swirl within RStudio. Also make sure that you have the latest version of swirl installed.

**Comment by kapilparashar** [comment]
@sahaisiddharth Seankross
I updated the swirl for recent version using this http://swirlstats.com/faq.html
> install.packages("devtools")
> library(devtools)
> install_github("swirldev/swirl")
> library(swirl)
> swirl()
also tried swirl with Rstudio but result not effected

![image](https://cloud.githubusercontent.com/assets/20329015/16740541/1341fabc-4765-11e6-8f8c-d986be4b3b97.png)

**Comment by seankross** [comment]
@kapilparashar is there a script hiding in the RStudio source window?

**Comment by kapilparashar** [comment]
Yes, now it's clear

![image](https://cloud.githubusercontent.com/assets/20329015/16742479/75bd0a1c-476d-11e6-9b66-df1921a0ac99.png)

**Comment by seankross** [comment]
@kapilparashar save the script after changing it, and then enter `submit()` into the R console. I recommend you totally close and re-open RStudio before you attempt this.

**Comment by kapilparashar** [comment]
**Thanks a lot for your guidance. Please suggest how can i do same for (R x64 3.3.1). Means what problem there.I am new for this but enjoying whatever.**

![image](https://cloud.githubusercontent.com/assets/20329015/16742984/d6e0462c-476f-11e6-96aa-5954b19fac1a.png)

**Comment by prem92** [comment]
I am getting an error in functions course in swirl package.can any one pls help me on this.
I am using R studio 3.3.1
Thanks in advance.

| Sourcing your script...

| Not quite, but you're learning! Try again.

| Make sure to delete the pound sign so the last expression in the function is just x.

![funct_error](https://cloud.githubusercontent.com/assets/23734709/21889261/137922ba-d8ee-11e6-96b0-edc77067dcc5.PNG)

**Comment by seankross** [comment]
@prem92 Please read the question above for the answer.

**Comment by annie-mac** [comment]
Looks like Rstudio needs swirl commands like submit entered prefaced with swirl:: so typing swirl::submit() submits the code

**Comment by annie-mac** [comment]
oops sorry, didn't recognise submit() because I hadn't loaded using library(swirl) first

**Comment by akaEmma** [comment]
The solution of typing "options(editor = "internal")" worked for me only after restarting R.

**Comment by RexGalilae** [comment]
Using R Studio 1.1.456 and it doesn't work for me even after restarting
