### ISSUE TITLE
Coursera Assignment Upload - "Error in curl::handle_setopt(handle, .list = req$options)" Problem

### ISSUE THREAD

**Issue by scknkrbg** [swirldev/swirl#482]
Hi all, 

As I complete one section in the "R Programming" course, it expectedly asks to get it recorded on the Coursera. However, as I correctly enter my credentials, it gives the following error:

Error in curl::handle_setopt(handle, .list = req$options) : 
Unknown options: postfieldsize, postfields

| Leaving swirl now. Type swirl() to resume.

Anyone have any suggestions?

**Comment by samkulu** [comment]
Hello scknkrbg, 

I just had the same error message. 
The problem was that I had set the proxy server options completely wrong. 

In an earlier code version I have used a `proxy-server` string and a `proxy-port` string in different variables. I used the following code:


```
 httr::set_config(
    use_proxy(url = proxy[1], port = as.numeric(proxy[2]), username=proxy_user[1],password = proxy_user[2] , auth="any"),
    override = TRUE
 )
```

Then I switched to a more compact version with a single string `server:port`. Unfortunately I forgot to adjust the code and got the same error message as you.  
After I changed the code as shown below, everything worked smoothly again.  

```
 httr::set_config(
    use_proxy(url = proxy, username=proxy_user[1],password = proxy_user[2] , auth="any"),
    override = TRUE
 )
```

Thus it was actually due to a `Error in curl::handle_setopt(handle, .list = req$options) : 
  A libcurl function was given a bad argument`. Only the error happened much earlier than expected and I had to look for it longer because the error appeared later in the function call.
