### ISSUE TITLE
Writing Lesson on Managing Character Data

### ISSUE THREAD

**Issue by eefox** [swirldev/swirl#509]
Creating my own course on dealing with character data. I am currently writing a lesson on sub() and gsub(). My code works outside of swirl with no errors. 

When I get to the first task that involves using sub, it gives the right result, but then has an error and exits out of swirl.  Here is a screenshot of the error I get.

![issue](https://cloud.githubusercontent.com/assets/20465922/16856410/c8727df6-49ce-11e6-92b5-9a307aa14621.PNG)

And here is the code I used for the question.

![issue code](https://cloud.githubusercontent.com/assets/20465922/16856438/e00dc664-49ce-11e6-9b9a-42b4beed75f5.PNG)

Does anyone know why this is happening. Again, the code works outside of swirl with no error.

Also, here is the character vector that I am using:
`phones <- c("805.756.1111","805 543 1234","800-805-0000",
            "(805) 952-5468")`

Thanks

**Comment by seankross** [comment]
Hi! Thanks for trying to make a swirl course. I'll look into this deeper tomorrow, but for now a work-around would be to store the regex for a period in a variable (`full_stop <- "\\."`) and then use that as the first argument to `sub(full_stop, "-", phones[1])`. Sorry for the trouble and I'll make sure to get to the bottom of this.

**Comment by eefox** [comment]
Thank you! That works for now, but if you find another solution please let me know.

**Comment by seankross** [comment]
Hi @eefox,

I figured this one out:

For your AnswerTest you should write:

```
omnitest(correctExpr='sub("\x5c\x5c.", "-", phones[1])')
```

This is based on the [hex value for backslash](http://ascii.cl/).

Let me know if this works for you!

**Comment by jonmcalder** [comment]
Hi @seankross,

I ran into this problem a few weeks ago and had been meaning to refer back to this thread at some stage. So glad that I have managed to find it again and that you have since figured it out. 

I get that this is kinda edge case-y due to all the parsing of expressions that swirl has to do behind the scenes, but I was wondering whether it would be feasible to include an explanation of this in the swirlify documentation somewhere? (e.g. [here](http://swirlstats.com/swirlify/writing.html))

I'm only a sample of one so not sure how representative I am, but I relied heavily on that section of documentation to get an idea of how to write questions and tests (e.g. as opposed to using the [swirl-courses](https://github.com/swirldev/swirl_courses) content for examples), and have referred back to it often, so I'm pretty sure if you could include a note there about needing to use "\x5c" instead of "\\" for AnswerTests that would help others like @eefox & I when attempting to test anything regex related.

**Comment by seankross** [comment]
@jonmcalder I agree this should be added to the documentation.
