### ISSUE TITLE
Swirl - Issue Unanswered till now

### ISSUE THREAD

**Issue by RabindraNP** [swirldev/swirl#830]
I am taking an online course on R Programming through Coursera. In the course, at the stage of 1 st week where there is a lesson of "swirl" I face a problem as follows;

Facing the same problem when I assigned x <- 5+7  in swirl,   RStudio stops working and the message displayed as R session Aborted. R encounters a fatal error. The session was terminated and with a new option: Start New Session. I don't see any solution here till now, please.

Waiting for your response.

**Comment by cpgitgig135** [comment]
Dear Mr. RabindraNP:

I am running swirl from within the RGui program (the R compiler that comes for 64 and 32 bit compiler). You only need to install one of them. It looks like you are running swirl within RStudio instead of from the R compiler, and I do not know if you should or if it would matter. I think that you may not have installed the R program, only the RStudio, but I do not know if it matters for swirl. Typing x <- 5+7 should definitely work in RStudio unless RStudio is damaged or maybe swirl does not work within RStudio, only inside the RGui (the plain R compiler). You can test RStudio without running swirl within it and see if it works okay. If RStudio does not work then you can reinstall RStudio. I am an R student like you though, not an instructor.
Cesar

**Comment by RabindraNP** [comment]
Dear cpgitgig135:

Thank you so much. yeah, there were problems  but now everything fine. I reinstalled  RStudion. Now perfectly working :).
